// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuH_Z70ozC41Dhuzz0tKb5Hx3VoiBFLTY',
    appId: '1:829066508421:web:c1757761ad50f2515a51ec',
    messagingSenderId: '829066508421',
    projectId: 'astute-empire',
    authDomain: 'astute-empire.firebaseapp.com',
    storageBucket: 'astute-empire.firebasestorage.app',
    measurementId: 'G-8TV87WQFD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuH_Z70ozC41Dhuzz0tKb5Hx3VoiBFLTY',
    appId: '1:829066508421:android:c1757761ad50f2515a51ec',
    messagingSenderId: '829066508421',
    projectId: 'astute-empire',
    authDomain: 'astute-empire.firebaseapp.com',
    storageBucket: 'astute-empire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuH_Z70ozC41Dhuzz0tKb5Hx3VoiBFLTY',
    appId: '1:829066508421:ios:c1757761ad50f2515a51ec',
    messagingSenderId: '829066508421',
    projectId: 'astute-empire',
    authDomain: 'astute-empire.firebaseapp.com',
    storageBucket: 'astute-empire.firebasestorage.app',
    iosBundleId: 'com.sureboda.surebodaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuH_Z70ozC41Dhuzz0tKb5Hx3VoiBFLTY',
    appId: '1:829066508421:ios:c1757761ad50f2515a51ec',
    messagingSenderId: '829066508421',
    projectId: 'astute-empire',
    authDomain: 'astute-empire.firebaseapp.com',
    storageBucket: 'astute-empire.firebasestorage.app',
    iosBundleId: 'com.sureboda.surebodaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuH_Z70ozC41Dhuzz0tKb5Hx3VoiBFLTY',
    appId: '1:829066508421:web:c1757761ad50f2515a51ec',
    messagingSenderId: '829066508421',
    projectId: 'astute-empire',
    authDomain: 'astute-empire.firebaseapp.com',
    storageBucket: 'astute-empire.firebasestorage.app',
    measurementId: 'G-8TV87WQFD3',
  );
}
